version: "3.8"

services:
  nginx: # --------------------------------------------------------------------
    build:
      context: requirements/nginx # https://stackoverflow.com/a/35260151
      args:
        domain_name: $DOMAIN_NAME
        ssl_crt: $SSL_CERTIFICATE
        ssl_key: $SSL_CERTIFICATE_KEY
    container_name: nginx
    ports:
      - "443:443" # host_port:container_port
#     - target: 443 # container port
#       published: 443 # host port
#       protocol: tcp
#       mode: host
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/inception
#   restart: always
  wordpress: # ----------------------------------------------------------------
    build: requirements/wordpress
    container_name: wordpress
    expose:
      - "3306"
      - "9000"
#   depends_on:
#     mariadb:
#       condition: service_started # service_ [ started | healthy | completed_successfully ]
#   restart: always
  mariadb: # ------------------------------------------------------------------
    build:
      context: requirements/mariadb
      args:
        mysql_root_password: $MYSQL_ROOT_PASSWORD
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    # - mariadb:$(MYSQL_DATA_DIRECTORY)
    expose:
      - "3306"
#   restart: always
# -----------------------------------------------------------------------------
volumes:
  wordpress:
    driver: local # local-persist (?)
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/wordpress
  mariadb:
    driver: local # local-persist (?)
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/mariadb
# -----------------------------------------------------------------------------
networks:
  default:
    name: inception
# -----------------------------------------------------------------------------
# labels:
#   com.docker.compose.project: "inception"

# configs:
# name: "inception"

# About `restart`
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#restart
# https://github.com/compose-spec/compose-spec/blob/master/deploy.md#restart_policy
# https://serverfault.com/a/884823

# About `depends_on`
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck
# https://www.baeldung.com/ops/docker-compose-links-depends-on

# About network
# https://docs.docker.com/compose/networking/
# https://www.aquasec.com/cloud-native-academy/docker-container/docker-networking/
# https://www.baeldung.com/ops/docker-compose-expose-vs-ports
# https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
# https://docs.docker.com/compose/compose-file/compose-file-v3/#expose

# About env
# https://docs.docker.com/compose/environment-variables/
# https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file
# https://vsupalov.com/docker-arg-env-variable-guide/

# About secrets (not needed _at all_ by the subject)
# https://docs.docker.com/engine/swarm/secrets/
# https://www.rockyourcode.com/using-docker-secrets-with-docker-compose/

# TODO
# on host, set owner for docker volumes (systemd-resolve:systemd-journal by default)
# add `COMPOSE_PROJECT_NAME=inception` into `.env` -- or add top-level `name: "inception"` here
