version: "3.8"

services:
  nginx: # --------------------------------------------------------------------
    build:
      context: requirements/nginx # https://stackoverflow.com/a/35260151
      args:
        domain_name: $DOMAIN_NAME
        ssl_crt: $SSL_CERTIFICATE
        ssl_key: $SSL_CERTIFICATE_KEY
    container_name: nginx
    hostname: nginx
    ports:
      - "443:443"
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/inception
    depends_on:
      wordpress:
        condition: service_started # service_ [ started | healthy | completed_successfully ]
    restart: always
  wordpress: # ----------------------------------------------------------------
    build:
      context: requirements/wordpress
      args:
        db_host: $DB_HOST
        db_name: $DB_NAME
        db_user: $DB_USER
        db_pass: $DB_PASS
        db_prefix: $DB_PREFIX
        wp_url: $WP_URL
        wp_title: $WP_TITLE
        wp_debug: $WP_DEBUG
        wp_admin_user: $WP_ADMIN_USER
        wp_admin_pass: $WP_ADMIN_PASS
        wp_admin_mail: $WP_ADMIN_MAIL
    container_name: wordpress
    hostname: wordpress
    expose:
      - "3306"
      - "9000"
    depends_on:
      mariadb:
        condition: service_started # service_ [ started | healthy | completed_successfully ]
    volumes:
      - wordpress:/var/www/inception
    restart: always
  mariadb: # ------------------------------------------------------------------
    build:
      context: requirements/mariadb
      args:
        mysql_root_password: $MYSQL_ROOT_PASSWORD
        mysql_user_name: $MYSQL_USER_NAME
        mysql_user_pass: $MYSQL_USER_PASS
        mysql_debug: $MYSQL_DEBUG
        db_name: $DB_NAME
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadb:$MYSQL_DATA_DIRECTORY
    expose:
      - "3306"
    restart: always
# -----------------------------------------------------------------------------
volumes:
  wordpress:
    driver: local # local-persist (?)
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/wordpress
  mariadb:
    driver: local # local-persist (?)
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/mariadb
# -----------------------------------------------------------------------------
networks:
  default:
    name: inception
# -----------------------------------------------------------------------------
# labels:
#   com.docker.compose.project: "inception"

# configs:
# name: "inception"

# About `restart`
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#restart
# https://github.com/compose-spec/compose-spec/blob/master/deploy.md#restart_policy
# https://serverfault.com/a/884823
# https://docs.docker.com/config/containers/start-containers-automatically/#restart-policy-details

# About `depends_on`
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck
# https://www.baeldung.com/ops/docker-compose-links-depends-on

# About network
# https://docs.docker.com/compose/networking/
# https://www.aquasec.com/cloud-native-academy/docker-container/docker-networking/
# https://www.baeldung.com/ops/docker-compose-expose-vs-ports
# https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
# https://docs.docker.com/compose/compose-file/compose-file-v3/#expose

# About env
# https://docs.docker.com/compose/environment-variables/
# https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file
# https://vsupalov.com/docker-arg-env-variable-guide/

# About secrets (not needed _at all_ by the subject)
# https://docs.docker.com/engine/swarm/secrets/
# https://www.rockyourcode.com/using-docker-secrets-with-docker-compose/

# TODO
# on host, set owner for docker volumes (systemd-resolve:systemd-journal by default)
# add `COMPOSE_PROJECT_NAME=inception` into `.env` -- or add top-level `name: "inception"` here
