version: "3.8"

services:
  nginx: # --------------------------------------------------------------------
    build:
      context: requirements/nginx
      args:
        domain_name: $DOMAIN_NAME
        ssl_crt: $SSL_CERTIFICATE
        ssl_key: $SSL_CERTIFICATE_KEY
    container_name: nginx
    hostname: nginx
    ports:
      - "443:443"
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/inception
    depends_on:
      wordpress:
        condition: service_started
    restart: always
  wordpress: # ----------------------------------------------------------------
    build:
      context: requirements/wordpress
      args:
        db_host: $DB_HOST
        db_name: $DB_NAME
        db_user: $DB_USER
        db_pass: $DB_PASS
        db_prefix: $DB_PREFIX
        wp_dir: $WP_DIR
        wp_url: $WP_URL
        wp_title: $WP_TITLE
        wp_debug: $WP_DEBUG
        wp_admin_user: $WP_ADMIN_USER
        wp_admin_pass: $WP_ADMIN_PASS
        wp_admin_mail: $WP_ADMIN_MAIL
        wp_regular_user: $WP_REGULAR_USER
        wp_regular_pass: $WP_REGULAR_PASS
        wp_regular_mail: $WP_REGULAR_MAIL
    container_name: wordpress
    hostname: wordpress
    expose:
      - "3306"
      - "9000"
    depends_on:
      mariadb:
        condition: service_started
    volumes:
      - wordpress:/var/www/inception
    restart: always
  mariadb: # ------------------------------------------------------------------
    build:
      context: requirements/mariadb
      args:
        mysql_root_password: $MYSQL_ROOT_PASSWORD
        mysql_user_name: $MYSQL_USER_NAME
        mysql_user_pass: $MYSQL_USER_PASS
        mysql_debug: $MYSQL_DEBUG
        db_name: $DB_NAME
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadb:$MYSQL_DATA_DIRECTORY
    expose:
      - "3306"
    restart: always
# -----------------------------------------------------------------------------
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/mariadb
# -----------------------------------------------------------------------------
networks:
  default:
    name: inception
# -----------------------------------------------------------------------------
