version: "3.8"

name: "inception"

# For each service, `image` section is omitted since `build` section is defined.
# However `build` is not guaranteed to be supported by any compose implementation.
# (cf. https://docs.docker.com/compose/compose-file/build/)
services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
  #  wordpress:
  #    build: requirements/wordpress
  mariadb:
    build: requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
    volumes:
      - db_mariadb:/home/trobin/

volumes:
  #  db_wordpress:
  db_mariadb:
    driver: local # local-persist
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/mariadb

# secrets:
# configs:
