version: "3.8"

#name: "inception"

# For each service, `image` section is omitted since `build` section is defined.
# However `build` is not guaranteed to be supported by any compose implementation.
# (cf. https://docs.docker.com/compose/compose-file/build/)
services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - db_wordpress:/home/trobin/data/www
  #  wordpress:
  #    build: requirements/wordpress
  mariadb:
    build: requirements/mariadb
      #    environment:
      #      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
    volumes:
      - db_mariadb:/home/trobin/data/mariadb

# todo: remove 'db_' prefix
volumes:
  db_wordpress:
    driver: local # local-persist
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/www
  db_mariadb:
    driver: local # local-persist
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/mariadb

# secrets:
# configs:
