version: "3.8"

services:
  nginx: # --------------------------------------------------------------------
    build: requirements/nginx
    ports:
      - "443:443" # host_port:container_port
      #   - target: 443 # container port
      #     published: 443 # host port
      #     protocol: tcp
      #     mode: host
    expose:
      - "9000"
    volumes:
      - db_wordpress:/var/www/inception
    restart: always
    env_file: .env
  wordpress: # ----------------------------------------------------------------
    build: requirements/wordpress
    restart: always
    expose:
      - "3306"
      - "9000"
        #  depends_on:
        #    mariadb:
        #      condition: service_started # service_ [ started | healthy | completed_successfully ]
  mariadb: # ------------------------------------------------------------------
    build: requirements/mariadb
    volumes:
      - db_mariadb:/var/lib/mysql
    # - db_mariadb:$(MYSQL_DATA_DIRECTORY)
    restart: always
    expose:
      - "3306"
    # container_name: inception-mariadb
    #    environment:
    #      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
# -----------------------------------------------------------------------------

# todo: remove 'db_' prefix
volumes:
  db_wordpress:
    driver: local # local-persist (?)
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/wordpress
  db_mariadb:
    driver: local # local-persist (?)
    driver_opts:
      type: none
      o: bind
      device: /home/trobin/data/mariadb

networks:
  default:
    name: inception
      #  labels:
      #    com.docker.compose.project: "inception"

# secrets:
# configs:
# name: "inception"

# About `restart`
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#restart
# https://github.com/compose-spec/compose-spec/blob/master/deploy.md#restart_policy
# https://serverfault.com/a/884823

# About `depends_on`
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck
# https://www.baeldung.com/ops/docker-compose-links-depends-on

# About network
# https://docs.docker.com/compose/networking/
# https://www.aquasec.com/cloud-native-academy/docker-container/docker-networking/
# https://www.baeldung.com/ops/docker-compose-expose-vs-ports
# https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
# https://docs.docker.com/compose/compose-file/compose-file-v3/#expose

# About env
# https://docs.docker.com/compose/environment-variables/
# https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file

# TODO
# on host, set owner for docker volumes (systemd-resolve:systemd-journal by default)
# add `COMPOSE_PROJECT_NAME=inception` into `.env` -- or add top-level `name: "inception"` here
